# Section 1: Python Basics (Data Structures)

In [94]:
list1=[]
for i in range(10,101,10):
    list1.append(i)
print(f'First element of the list is -> {list1[0]}')
print(f'Last element of the list is -> {list1[-1]}')
print(f"Reversed List is :- \n{list1[::-1]}")

First element of the list is -> 10
Last element of the list is -> 100
Reversed List is :-
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]

In [95]:
list1.append(60)
print(list1)
list1.remove(30)
print(list1)
print(f'Sorted List in descending Order is :- {sorted(list1,reverse=True)}')

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 60]
[10, 20, 40, 50, 60, 70, 80, 90, 100, 60]
Sorted List in descending Order is :- [100, 90, 80, 70, 60, 60, 50, 40, 20, 10]

In [96]:
dict1={'Name':'Ramanand Pandey','Age':25,'City':'Nawada Bihar'}
print('Iterating through dict and printing key and value')
for k,v in dict1.items():
    print(k,':->',v)
dict1['Salary']=50000
print(dict1)

Iterating through dict and printing key and value
Name :-> Ramanand Pandey
Age :-> 25
City :-> Nawada Bihar
{'Name': 'Ramanand Pandey', 'Age': 25, 'City': 'Nawada Bihar', 'Salary': 50000}

In [97]:
print('Printing number 1-20')
for i in range(1,21):
    print(i,end=' ')
print()
print('Printing Even number till 20')
for i in range(1,21):
    if not i%2:
        print(i,end=' ')

Printing number 1-20
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
Printing Even number till 20
2 4 6 8 10 12 14 16 18 20

In [99]:
def squared(n):
    return n*n
for i in range(3):
    n=int(input('Enter the number:-\n'))
    print(f'Squaure of {n} is :-> {squared(n)}')

Enter the number:-
 5

Squaure of 5 is :-> 25

Enter the number:-
 10

Squaure of 10 is :-> 100

Enter the number:-
 15

Squaure of 15 is :-> 225

In [100]:
squarelist=[s*s for s in range(1,11)]
print(squarelist)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# Section 2: NumPy Basics

In [101]:
import sys
!{sys.executable} -m pip install numpy

Requirement already satisfied: numpy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.4)

In [102]:
import numpy as np
arr1=[10,5,20,12,50,100]
data=np.array(arr1)
print(f'List to numpy arr is :-> {data}')
print(f'Zeros array :-> {np.zeros(5,dtype=int)}')
print(f'Ones array :-> {np.ones(5)}')
print(f'Shape of the array is :-> {data.shape}')
print(f'Dimension of the array is :-> {data.ndim}')
print(f'Data Type of the array is :-> {data.dtype}')

List to numpy arr is :-> [ 10   5  20  12  50 100]
Zeros array :-> [0 0 0 0 0]
Ones array :-> [1. 1. 1. 1. 1.]
Shape of the array is :-> (6,)
Dimension of the array is :-> 1
Data Type of the array is :-> int64

In [103]:
print(f'First element of the array is :-> {data[0]}')
print(f'Last 3 element of the array is :-> {data[-3:]}')

First element of the array is :-> 10
Last 3 element of the array is :-> [ 12  50 100]

In [104]:
print(f'All element in arr multiply by 2 is :-> {data*2}')
print(f'Average/Mean of the array is :-> {data.mean():.2f}')
print(f'Sum of the array is :-> {data.sum()}')

All element in arr multiply by 2 is :-> [ 20  10  40  24 100 200]
Average/Mean of the array is :-> 32.83
Sum of the array is :-> 197

In [105]:
data2=[10,20,20,1,2,3,80,90,100]
data2=np.array(data2)
data2=data2.reshape(3,3)
data2

array([[ 10,  20,  20],
       [  1,   2,   3],
       [ 80,  90, 100]])

In [106]:
print(f'data in the array greater than 20 is :-> {data2[data2>20]}')

data in the array greater than 20 is :-> [ 80  90 100]

In [107]:
print(f'10 random integer from 1 to 100 is :-> {np.random.randint(1,101,10)}')

10 random integer from 1 to 100 is :-> [81 56 68 27 27 94 36 69  3 95]

In [108]:
print(f'maximum element of the arr is :-> {data2.max()}')
print(f'Minimum element of the arr is :-> {data2.min()}')
print(f'Standard Deviation of the arr is :-> {data2.std():.3f}')

maximum element of the arr is :-> 100
Minimum element of the arr is :-> 1
Standard Deviation of the arr is :-> 38.881

# Section 3: Pandas Basics

In [109]:
import pandas as pd

In [158]:
df=pd.DataFrame({
    'Name':['Ramanand Pandey','Rohit Razz','Rahul Tiwari','Siddharth Mishra','Anshu Upadhyay','Priya','Rakhi'],
    'Age':[24,25,26,21,23,24,28],
    'Salary':[52000,48000,35000,25000,36000,18000,22000],
    'Department':['AI Engineer','Data Scientist','AI Engineer','Electrical Engineer','Electrical Engineer','HR','HR']
})
print(df)

               Name  Age  Salary           Department
0   Ramanand Pandey   24   52000          AI Engineer
1        Rohit Razz   25   48000       Data Scientist
2      Rahul Tiwari   26   35000          AI Engineer
3  Siddharth Mishra   21   25000  Electrical Engineer
4    Anshu Upadhyay   23   36000  Electrical Engineer
5             Priya   24   18000                   HR
6             Rakhi   28   22000                   HR

In [159]:
print(df.head())
print('--------------------------')
print(df.tail())
print('---------------------------')
print(df.columns)

               Name  Age  Salary           Department
0   Ramanand Pandey   24   52000          AI Engineer
1        Rohit Razz   25   48000       Data Scientist
2      Rahul Tiwari   26   35000          AI Engineer
3  Siddharth Mishra   21   25000  Electrical Engineer
4    Anshu Upadhyay   23   36000  Electrical Engineer
--------------------------
               Name  Age  Salary           Department
2      Rahul Tiwari   26   35000          AI Engineer
3  Siddharth Mishra   21   25000  Electrical Engineer
4    Anshu Upadhyay   23   36000  Electrical Engineer
5             Priya   24   18000                   HR
6             Rakhi   28   22000                   HR
---------------------------
Index(['Name', 'Age', 'Salary', 'Department'], dtype='str')

In [160]:
print(df['Name'])

0     Ramanand Pandey
1          Rohit Razz
2        Rahul Tiwari
3    Siddharth Mishra
4      Anshu Upadhyay
5               Priya
6               Rakhi
Name: Name, dtype: str

In [161]:
print(df[df['Age']>25])

           Name  Age  Salary   Department
2  Rahul Tiwari   26   35000  AI Engineer
6         Rakhi   28   22000           HR

In [162]:
df['Bonus']=df['Salary']*0.1
print(df)

               Name  Age  Salary           Department   Bonus
0   Ramanand Pandey   24   52000          AI Engineer  5200.0
1        Rohit Razz   25   48000       Data Scientist  4800.0
2      Rahul Tiwari   26   35000          AI Engineer  3500.0
3  Siddharth Mishra   21   25000  Electrical Engineer  2500.0
4    Anshu Upadhyay   23   36000  Electrical Engineer  3600.0
5             Priya   24   18000                   HR  1800.0
6             Rakhi   28   22000                   HR  2200.0

In [163]:
print(f'Average Salary of the employee is :-> {df['Salary'].mean():.2f}')
print(f'Max Salary of the employee is :-> {df['Salary'].max()}')
print(f'Min Salary of the employee is :-> {df['Salary'].min()}')

Average Salary of the employee is :-> 33714.29
Max Salary of the employee is :-> 52000
Min Salary of the employee is :-> 18000

In [164]:
print(f'Sorted employee Based on the salary (less to high) is :-> {df.sort_values(by='Salary')}')
print('-------------------------------------------')
print(f'Sorted employee Based on the salary(High to less) is :-> {df.sort_values(by='Salary',ascending=False)}')

Sorted employee Based on the salary (less to high) is :->                Name  Age  Salary           Department   Bonus
5             Priya   24   18000                   HR  1800.0
6             Rakhi   28   22000                   HR  2200.0
3  Siddharth Mishra   21   25000  Electrical Engineer  2500.0
2      Rahul Tiwari   26   35000          AI Engineer  3500.0
4    Anshu Upadhyay   23   36000  Electrical Engineer  3600.0
1        Rohit Razz   25   48000       Data Scientist  4800.0
0   Ramanand Pandey   24   52000          AI Engineer  5200.0
-------------------------------------------
Sorted employee Based on the salary(High to less) is :->                Name  Age  Salary           Department   Bonus
0   Ramanand Pandey   24   52000          AI Engineer  5200.0
1        Rohit Razz   25   48000       Data Scientist  4800.0
4    Anshu Upadhyay   23   36000  Electrical Engineer  3600.0
2      Rahul Tiwari   26   35000          AI Engineer  3500.0
3  Siddharth Mishra   21   25000  Electrical Engineer  2500.0
6             Rakhi   28   22000                   HR  2200.0
5             Priya   24   18000                   HR  1800.0

In [165]:
df.loc[6,'Salary']=None
df

               Name  Age   Salary           Department   Bonus
0   Ramanand Pandey   24  52000.0          AI Engineer  5200.0
1        Rohit Razz   25  48000.0       Data Scientist  4800.0
2      Rahul Tiwari   26  35000.0          AI Engineer  3500.0
3  Siddharth Mishra   21  25000.0  Electrical Engineer  2500.0
4    Anshu Upadhyay   23  36000.0  Electrical Engineer  3600.0
5             Priya   24  18000.0                   HR  1800.0
6             Rakhi   28      NaN                   HR  2200.0

In [166]:
print(df.isnull())
print(df.isnull().sum())

    Name    Age  Salary  Department  Bonus
0  False  False   False       False  False
1  False  False   False       False  False
2  False  False   False       False  False
3  False  False   False       False  False
4  False  False   False       False  False
5  False  False   False       False  False
6  False  False    True       False  False
Name          0
Age           0
Salary        1
Department    0
Bonus         0
dtype: int64

In [167]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['Bonus']=df['Salary']*0.1
df['Salary']=df['Salary'].round(2)
df['Bonus']=df['Bonus'].round(2)
df

               Name  Age    Salary           Department    Bonus
0   Ramanand Pandey   24  52000.00          AI Engineer  5200.00
1        Rohit Razz   25  48000.00       Data Scientist  4800.00
2      Rahul Tiwari   26  35000.00          AI Engineer  3500.00
3  Siddharth Mishra   21  25000.00  Electrical Engineer  2500.00
4    Anshu Upadhyay   23  36000.00  Electrical Engineer  3600.00
5             Priya   24  18000.00                   HR  1800.00
6             Rakhi   28  35666.67                   HR  3566.67

In [170]:
print(df.groupby('Department')['Salary'].mean())

Department
AI Engineer            43500.000
Data Scientist         48000.000
Electrical Engineer    30500.000
HR                     26833.335
Name: Salary, dtype: float64

# Section 4: Mini Project

In [172]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ramanand','Rohit','Rahul','Priya','Anshu','Amit','Neha','Suman','Karan','None',
             'Vikas','Sneha','Arjun','Kriti','Nikhil','None','Manish','Tina','Deepak','Shreya'],
    
    'Marks': [78,92,85,None,88,55,73,81,90,60,
              77,84,69,None,82,58,76,89,None,65],
    
    'Department': ['CSE','Data Science','CSE','Web Dev','Data Science','AI','Web Dev','CSE','None','Web Dev',
                   'Data Science','CSE','AI','Data Science','None','Web Dev','AI','CSE','None','Web Dev']
})


df

        Name  Marks    Department
0   Ramanand   78.0           CSE
1      Rohit   92.0  Data Science
2      Rahul   85.0           CSE
3      Priya    NaN       Web Dev
4      Anshu   88.0  Data Science
5       Amit   55.0            AI
6       Neha   73.0       Web Dev
7      Suman   81.0           CSE
8      Karan   90.0          None
9       None   60.0       Web Dev
10     Vikas   77.0  Data Science
11     Sneha   84.0           CSE
12     Arjun   69.0            AI
13     Kriti    NaN  Data Science
14    Nikhil   82.0          None
15      None   58.0       Web Dev
16    Manish   76.0            AI
17      Tina   89.0           CSE
18    Deepak    NaN          None
19    Shreya   65.0       Web Dev

In [182]:
print(f'Max Marks of the Student is :-> {df['Marks'].max()}')
print(f'Average Marks of the Student is :-> {df['Marks'].mean():.2f}')
print(df[df['Marks']>80])
df.sort_values(by='Marks')

Max Marks of the Student is :-> 92.0
Average Marks of the Student is :-> 76.59
      Name  Marks    Department
1    Rohit   92.0  Data Science
2    Rahul   85.0           CSE
4    Anshu   88.0  Data Science
7    Suman   81.0           CSE
8    Karan   90.0          None
11   Sneha   84.0           CSE
14  Nikhil   82.0          None
17    Tina   89.0           CSE

        Name  Marks    Department
5       Amit   55.0            AI
15      None   58.0       Web Dev
9       None   60.0       Web Dev
19    Shreya   65.0       Web Dev
12     Arjun   69.0            AI
6       Neha   73.0       Web Dev
16    Manish   76.0            AI
10     Vikas   77.0  Data Science
0   Ramanand   78.0           CSE
7      Suman   81.0           CSE
14    Nikhil   82.0          None
11     Sneha   84.0           CSE
2      Rahul   85.0           CSE
4      Anshu   88.0  Data Science
17      Tina   89.0           CSE
8      Karan   90.0          None
1      Rohit   92.0  Data Science
3      Priya    NaN       Web Dev
13     Kriti    NaN  Data Science
18    Deepak    NaN          None

In [183]:
df.to_csv('Students.csv',index=False)

In [187]:
df2=pd.read_csv('Students.csv')

In [188]:
df2

        Name  Marks    Department
0   Ramanand   78.0           CSE
1      Rohit   92.0  Data Science
2      Rahul   85.0           CSE
3      Priya    NaN       Web Dev
4      Anshu   88.0  Data Science
5       Amit   55.0            AI
6       Neha   73.0       Web Dev
7      Suman   81.0           CSE
8      Karan   90.0           NaN
9        NaN   60.0       Web Dev
10     Vikas   77.0  Data Science
11     Sneha   84.0           CSE
12     Arjun   69.0            AI
13     Kriti    NaN  Data Science
14    Nikhil   82.0           NaN
15       NaN   58.0       Web Dev
16    Manish   76.0            AI
17      Tina   89.0           CSE
18    Deepak    NaN           NaN
19    Shreya   65.0       Web Dev

In [189]:
df2.describe()

           Marks
count  17.000000
mean   76.588235
std    11.646130
min    55.000000
25%    69.000000
50%    78.000000
75%    85.000000
max    92.000000

In [190]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        18 non-null     str
 1   Marks       17 non-null     float64
 2   Department  17 non-null     str
dtypes: float64(1), str(2)
memory usage: 612.0 bytes

In [192]:
df2.isnull().sum()

Name          2
Marks         3
Department    3
dtype: int64

In [200]:
df['Marks']=df['Marks'].fillna(df['Marks'].mean()).round(2)

In [201]:
df

        Name  Marks    Department
0   Ramanand  78.00           CSE
1      Rohit  92.00  Data Science
2      Rahul  85.00           CSE
3      Priya  76.59       Web Dev
4      Anshu  88.00  Data Science
5       Amit  55.00            AI
6       Neha  73.00       Web Dev
7      Suman  81.00           CSE
8      Karan  90.00           NaN
9        NaN  60.00       Web Dev
10     Vikas  77.00  Data Science
11     Sneha  84.00           CSE
12     Arjun  69.00            AI
13     Kriti  76.59  Data Science
14    Nikhil  82.00           NaN
15       NaN  58.00       Web Dev
16    Manish  76.00            AI
17      Tina  89.00           CSE
18    Deepak  76.59           NaN
19    Shreya  65.00       Web Dev

In [203]:
df.groupby('Department')['Marks'].mean().round(2)

Department
AI              66.67
CSE             83.40
Data Science    83.40
Web Dev         66.52
Name: Marks, dtype: float64

# Quick QNA?

List vs NumPy array?

A List is a built-in data type in Python that can store elements of different data types. It is flexible but slower compared to NumPy arrays because operations are performed using loops.

NumPy is a Python library used for numerical computations on arrays. A NumPy array stores elements of the same data type and performs operations much faster because it uses vectorized operations instead of loops.

Why NumPy faster?

NumPy is faster than normal Python lists because The Backend of numpy has written in c.
And also because it stores data in contiguous memory, 
ses a single data type, and performs vectorized operations with optimized low-level loops, 
which together reduce overhead and make computations much faster.

What is DataFrame?

A DataFrame is a two-dimensional data structure in Python that organizes data in the form of rows and columns. 
It is similar to an Excel sheet and is widely used for data analysis tasks such as data cleaning, 
transformation, and performing analytical operations.

.loc vs .iloc?

.loc is a pandas method used for label-based indexing, 
where rows and columns are accessed using their names (labels). 
For example: df.loc[0, 'Marks'].

.iloc is a pandas method used for integer position-based indexing, 
where rows and columns are accessed using their numerical index positions. 
For example: df.iloc[0, 1].